/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.House;
import model.Patient;
import model.VitalSigns;

/**
 *
 * @author Disha
 */
public class EncounterHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EncounterHistoryJPanel
     */
    EncounterHistory encounterHistory;
    public EncounterHistoryJPanel(EncounterHistory encounterHistory) {
        initComponents();
        
        this.encounterHistory = encounterHistory; 
        
        populateEncounterHistoryTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleEncounterHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounterHistory = new javax.swing.JTable();

        lblTitleEncounterHistory.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitleEncounterHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleEncounterHistory.setText("Patient Encounter History.");

        tblEncounterHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient Id", "Encounter Number", "Community", "Age", "Gender", "Contact Number", "Street Name", "House Number", "City", "State", "Zip Code", "BP", "Sugar", "HR", "BMI", "Temp"
            }
        ));
        jScrollPane1.setViewportView(tblEncounterHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleEncounterHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitleEncounterHistory)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitleEncounterHistory;
    private javax.swing.JTable tblEncounterHistory;
    // End of variables declaration//GEN-END:variables

    private void populateEncounterHistoryTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblEncounterHistory.getModel();
        model.setRowCount(0);
        
        for(Encounter e: encounterHistory.getEncounterHistory()){
            Object[] row = new Object[17];
            
            Patient p = e.getEncounterPatient();
            House h = p.getHouse();
            VitalSigns vs = p.getVitals();
            
            row[0] = p;
            row[1] = p.getPatientId();
            row[2] = e.getEncounterNumber();
            row[3] = h.getCommunity();
            row[4] = p.getPatientAge();
            row[5] = p.getPatientSex();
            row[6] = p.getPatientContactNumber();
            row[7] = h.getStreetName();
            row[8] = h.getHouseNumber();
            row[9] = h.getCity();
            row[10] = h.getState();
            row[11] = h.getZipCode();
            row[12] = vs.getBloodPressure();
            row[13] = vs.getSugar();
            row[14] = vs.getHeartRate();
            row[15] = vs.getBmi();
            row[16] = vs.getTemperature();
            
            model.addRow(row);
        }
    }
}
