/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import model.City;
import model.Community;
import model.EncounterHistory;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author Disha
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    PersonDirectory personDirectory;
    Community houseDirectory;
    City communityDirectory;
    PatientDirectory patientDirectory;
    EncounterHistory encounterHistory;
    
    public MainJFrame() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setSize(550, 350);
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        personDirectory = new PersonDirectory();
        houseDirectory = new Community();
        communityDirectory = new City();
        patientDirectory = new PatientDirectory();
        encounterHistory = new EncounterHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlArea = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        btnPatientFirstEncounter = new javax.swing.JButton();
        btnPatientEncounter = new javax.swing.JButton();
        btnEncounterHistory = new javax.swing.JButton();
        btnSearchStats = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(200);

        controlArea.setBackground(new java.awt.Color(255, 51, 51));

        createButton.setText("Create Person");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        viewButton.setText("View Person");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        btnPatientFirstEncounter.setText("Patient's First Encounter");
        btnPatientFirstEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientFirstEncounterActionPerformed(evt);
            }
        });

        btnPatientEncounter.setText("Patient Encounter");
        btnPatientEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientEncounterActionPerformed(evt);
            }
        });

        btnEncounterHistory.setText("Encounter History");
        btnEncounterHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterHistoryActionPerformed(evt);
            }
        });

        btnSearchStats.setText("Search Stats");
        btnSearchStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlAreaLayout = new javax.swing.GroupLayout(controlArea);
        controlArea.setLayout(controlAreaLayout);
        controlAreaLayout.setHorizontalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPatientFirstEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPatientEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchStats, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        controlAreaLayout.setVerticalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(createButton)
                .addGap(28, 28, 28)
                .addComponent(viewButton)
                .addGap(32, 32, 32)
                .addComponent(btnPatientFirstEncounter)
                .addGap(30, 30, 30)
                .addComponent(btnPatientEncounter)
                .addGap(30, 30, 30)
                .addComponent(btnEncounterHistory)
                .addGap(30, 30, 30)
                .addComponent(btnSearchStats)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlArea);

        workArea.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        CreateJPanel createPanel = new CreateJPanel(personDirectory,houseDirectory,communityDirectory);
        splitPane.setRightComponent(createPanel);

    }//GEN-LAST:event_createButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:

        ViewJPanel viewPanel = new ViewJPanel(personDirectory,houseDirectory,communityDirectory);
        splitPane.setRightComponent(viewPanel);

    }//GEN-LAST:event_viewButtonActionPerformed

    private void btnPatientFirstEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientFirstEncounterActionPerformed
        // TODO add your handling code here:
        PatientFirstEncounterJPanel patientFirstEncounterPanel = new PatientFirstEncounterJPanel(personDirectory,patientDirectory,encounterHistory);
        splitPane.setRightComponent(patientFirstEncounterPanel);
        
    }//GEN-LAST:event_btnPatientFirstEncounterActionPerformed

    private void btnPatientEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientEncounterActionPerformed
        // TODO add your handling code here:
        
        PatientEncounterPanel patientEncounterPanel = new PatientEncounterPanel(patientDirectory,encounterHistory);
        splitPane.setRightComponent(patientEncounterPanel);
         
    }//GEN-LAST:event_btnPatientEncounterActionPerformed

    private void btnEncounterHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterHistoryActionPerformed
        // TODO add your handling code here:
        
        EncounterHistoryJPanel encounterHistoryPanel = new EncounterHistoryJPanel(encounterHistory);
        splitPane.setRightComponent(encounterHistoryPanel); 
        
    }//GEN-LAST:event_btnEncounterHistoryActionPerformed

    private void btnSearchStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStatsActionPerformed
        // TODO add your handling code here:
        
        SearchStatsJPanel searchStatsPanel = new SearchStatsJPanel(patientDirectory);
        splitPane.setRightComponent(searchStatsPanel);
        
    }//GEN-LAST:event_btnSearchStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncounterHistory;
    private javax.swing.JButton btnPatientEncounter;
    private javax.swing.JButton btnPatientFirstEncounter;
    private javax.swing.JButton btnSearchStats;
    private javax.swing.JPanel controlArea;
    private javax.swing.JButton createButton;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton viewButton;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
