/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.House;
import model.Patient;
import model.PatientDirectory;
import model.VitalSigns;

/**
 *
 * @author Disha
 */
public class PatientEncounterPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientJPanel
     */
    PatientDirectory patientDirectory;
    EncounterHistory encounterHistory;
    
    public PatientEncounterPanel(PatientDirectory patientDirectory, EncounterHistory encounterHistory) {
        initComponents();
        
        this.patientDirectory = patientDirectory;
        this.encounterHistory = encounterHistory;
        
        populatePatientTable();
    }
    
    private int row;

    public int getRow() {
        return row;
    }

    public void setRow(int row) {
        this.row = row;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        txtSex = new javax.swing.JTextField();
        lblVitalBloodPressure = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        txtVitalBloodPressure = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        lblVitalSugar = new javax.swing.JLabel();
        txtVitalSugar = new javax.swing.JTextField();
        lblContactNumber = new javax.swing.JLabel();
        txtVitalHeartRate = new javax.swing.JTextField();
        lblStreeName = new javax.swing.JLabel();
        lblVitalHeartRate = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        txtVitalBmi = new javax.swing.JTextField();
        txtStreetName = new javax.swing.JTextField();
        lblVitalBmi = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblVitalTemperature = new javax.swing.JLabel();
        txtHouseNumber = new javax.swing.JTextField();
        txtVitalTemperature = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblTitlePV = new javax.swing.JLabel();
        lblHouseNumber = new javax.swing.JLabel();
        lblTitlePD = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        btnViewPatientData = new javax.swing.JButton();
        btnPatientEncounter = new javax.swing.JButton();
        lblSearchPatientId = new javax.swing.JLabel();
        txtSearchPatientId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblDisplayId = new javax.swing.JLabel();

        lblTitleP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitleP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleP.setText("Patient");

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient Id", "Blood Pressure", "Sugar", "Heart Rate", "BMI", "Temperature"
            }
        ));
        jScrollPane1.setViewportView(tblPatient);

        txtSex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblVitalBloodPressure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalBloodPressure.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalBloodPressure.setText("Blood Pressure:");

        txtZipCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtVitalBloodPressure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtContactNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblZipCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblZipCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZipCode.setText("Zip Code:");

        lblVitalSugar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalSugar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalSugar.setText("Sugar Level:");

        txtVitalSugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblContactNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContactNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContactNumber.setText("Contact Number:");

        txtVitalHeartRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblStreeName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStreeName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreeName.setText("Street Name:");

        lblVitalHeartRate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalHeartRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalHeartRate.setText("Heart Rate:");

        txtCommunity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityActionPerformed(evt);
            }
        });

        txtVitalBmi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtStreetName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblVitalBmi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalBmi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalBmi.setText("BMI:");

        lblCommunity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCommunity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCommunity.setText("Community:");

        lblVitalTemperature.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalTemperature.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalTemperature.setText("Temperature:");

        txtHouseNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtVitalTemperature.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTitlePV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitlePV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePV.setText("Patient's Vitals");

        lblHouseNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHouseNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHouseNumber.setText("House Number:");

        lblTitlePD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitlePD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePD.setText("Patient's Data");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");

        txtCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");

        lblCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblState.setText("State:");

        lblSex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSex.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSex.setText("Gender:");

        txtState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnViewPatientData.setText("View Patient Data");
        btnViewPatientData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientDataActionPerformed(evt);
            }
        });

        btnPatientEncounter.setText("Add Patient Encounter");
        btnPatientEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientEncounterActionPerformed(evt);
            }
        });

        lblSearchPatientId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchPatientId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSearchPatientId.setText("Patient Id:");

        lblId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(lblTitlePD, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(530, 530, 530)
                        .addComponent(btnViewPatientData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearchPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVitalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVitalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVitalHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVitalHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVitalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVitalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblVitalSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtVitalSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblVitalBmi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtVitalBmi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(btnPatientEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDisplayId, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStreeName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTitlePV, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(361, 361, 361)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPatientData)
                .addGap(27, 27, 27)
                .addComponent(lblTitlePD)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisplayId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStreeName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblTitlePV)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVitalSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVitalSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVitalBmi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVitalBmi)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVitalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVitalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVitalHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVitalHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVitalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVitalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPatientEncounter)))
                .addGap(48, 48, 48))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDisplayId, txtCommunity});

    }// </editor-fold>//GEN-END:initComponents

    private void txtCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityActionPerformed

    private void btnViewPatientDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientDataActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblPatient.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please Select a row to View!!!");
            return;
        } 

        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        Patient selectedPatient = (Patient) model.getValueAt(selectedRowIndex, 0);
        setRow(selectedRowIndex);
        House houseForView = selectedPatient.getHouse();
        
        lblDisplayId.setText(String.valueOf(selectedPatient.getPatientId()));
        txtCommunity.setText(houseForView.getCommunity());
        txtName.setText(selectedPatient.getPatientName());
        txtContactNumber.setText(String.valueOf(selectedPatient.getPatientContactNumber()));
        txtAge.setText(String.valueOf(selectedPatient.getPatientAge()));
        txtSex.setText(selectedPatient.getPatientSex());
        txtStreetName.setText(houseForView.getStreetName());
        txtHouseNumber.setText(String.valueOf(houseForView.getHouseNumber()));
        txtCity.setText(houseForView.getCity());
        txtState.setText(houseForView.getState());
        txtZipCode.setText(String.valueOf(houseForView.getZipCode()));
        
    }//GEN-LAST:event_btnViewPatientDataActionPerformed

    private void btnPatientEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientEncounterActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(lblDisplayId.getText());
        String communityName = txtCommunity.getText();
        String name = txtName.getText();
        long contactNumber = Long.parseLong(txtContactNumber.getText());
        int age = Integer.parseInt(txtAge.getText());
        String sex = txtSex.getText();
        String streetName = txtStreetName.getText();
        int houseNumber = Integer.parseInt(txtHouseNumber.getText());
        String city = txtCity.getText();
        String state = txtState.getText();
        int zipCode = Integer.parseInt(txtZipCode.getText());
        int bloodPressure = Integer.parseInt(txtVitalBloodPressure.getText());
        int sugar = Integer.parseInt(txtVitalSugar.getText());
        int heartRate = Integer.parseInt(txtVitalHeartRate.getText());
        int bmi = Integer.parseInt(txtVitalBmi.getText());
        int temperature = Integer.parseInt(txtVitalTemperature.getText());
        
        Encounter encounterPatient = encounterHistory.addEncounter();
        
        Patient patientNewEncounter = new Patient();
        House houseForPatient = new House();
        VitalSigns vs = new VitalSigns();
        
        int encounterNumber; 
        //List<Encounter> searchedPatientByEncounter = encounterHistory.findPatientById(id);
        //encounterNumber = searchedPatientByEncounter.size() + 1;
        encounterNumber = encounterHistory.findPatientById(id) + 1;
        //encounterNumber = 2;
        
        encounterPatient.setEncounterNumber(encounterNumber);
        patientNewEncounter.setPatientId(id);
        patientNewEncounter.setPatientName(name);
        patientNewEncounter.setPatientAge(age);
        patientNewEncounter.setPatientContactNumber(contactNumber);
        patientNewEncounter.setPatientSex(sex);
        
        houseForPatient.setCommunity(communityName);
        houseForPatient.setStreetName(streetName);
        houseForPatient.setHouseNumber(houseNumber);
        houseForPatient.setCity(city);
        houseForPatient.setState(state);
        houseForPatient.setZipCode(zipCode);
        patientNewEncounter.setHouse(houseForPatient);
        
        vs.setBloodPressure(bloodPressure);
        vs.setHeartRate(heartRate);
        vs.setSugar(sugar);
        vs.setBmi(bmi);
        vs.setTemperature(temperature);
        patientNewEncounter.setVitals(vs);
        
        encounterPatient.setEncounterPatient(patientNewEncounter);
        
        //Update Patient Directory.
        int selectedRowIndex = getRow();
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        Patient selectedPatient = (Patient) model.getValueAt(selectedRowIndex, 0);
        
        selectedPatient.setVitals(vs);
        
        JOptionPane.showMessageDialog(this, "Patient Encounter added successfully!! And PatientDirectory updated sucessfully");
        
        lblId.setText("");
        txtCommunity.setText("");
        txtName.setText("");
        txtContactNumber.setText("");
        txtAge.setText("");
        txtSex.setText("");
        txtStreetName.setText("");
        txtHouseNumber.setText("");
        txtCity.setText("");
        txtState.setText("");
        txtZipCode.setText("");
        txtVitalBloodPressure.setText("");
        txtVitalBmi.setText("");
        txtVitalHeartRate.setText("");
        txtVitalSugar.setText("");
        txtVitalTemperature.setText("");
        
    }//GEN-LAST:event_btnPatientEncounterActionPerformed

    private void populatePatientTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        model.setRowCount(0);
        
        for(Patient p: patientDirectory.getPatientDirectory()){
            Object[] row = new Object[7];
            
            VitalSigns vs = p.getVitals();
            row[0] = p;
            row[1] = p.getPatientId();
            row[2] = vs.getBloodPressure();
            row[3] = vs.getSugar();
            row[4] = vs.getHeartRate();
            row[5] = vs.getBmi();
            row[6] = vs.getTemperature();
            
            model.addRow(row);
        }
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPatientEncounter;
    private javax.swing.JButton btnViewPatientData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblDisplayId;
    private javax.swing.JLabel lblHouseNumber;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSearchPatientId;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreeName;
    private javax.swing.JLabel lblTitleP;
    private javax.swing.JLabel lblTitlePD;
    private javax.swing.JLabel lblTitlePV;
    private javax.swing.JLabel lblVitalBloodPressure;
    private javax.swing.JLabel lblVitalBmi;
    private javax.swing.JLabel lblVitalHeartRate;
    private javax.swing.JLabel lblVitalSugar;
    private javax.swing.JLabel lblVitalTemperature;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtHouseNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearchPatientId;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetName;
    private javax.swing.JTextField txtVitalBloodPressure;
    private javax.swing.JTextField txtVitalBmi;
    private javax.swing.JTextField txtVitalHeartRate;
    private javax.swing.JTextField txtVitalSugar;
    private javax.swing.JTextField txtVitalTemperature;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

   
}
