/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.House;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSigns;

/**
 *
 * @author Disha
 */
public class PatientFirstEncounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    EncounterHistory encounterHistory;
    
    public PatientFirstEncounterJPanel(PersonDirectory personDirectory,PatientDirectory patientDirectory, EncounterHistory encounterHistory) {
        initComponents();
        
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.encounterHistory = encounterHistory;
        
        populatePersonTable();
        populatePatientTable();
        populateEncounterTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        lblTitleP = new javax.swing.JLabel();
        lblSearchName = new javax.swing.JLabel();
        txtSearchbyName = new javax.swing.JTextField();
        btnSearchbyName = new javax.swing.JButton();
        txtSex = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        lblStreeName = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        txtStreetName = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();
        txtHouseNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblHouseNumber = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        btnFirstEncounter = new javax.swing.JButton();
        btnPersonAsPatient = new javax.swing.JButton();
        lblVitalBloodPressure = new javax.swing.JLabel();
        txtVitalBloodPressure = new javax.swing.JTextField();
        lblVitalSugar = new javax.swing.JLabel();
        txtVitalSugar = new javax.swing.JTextField();
        txtVitalHeartRate = new javax.swing.JTextField();
        lblVitalHeartRate = new javax.swing.JLabel();
        txtVitalBmi = new javax.swing.JTextField();
        lblVitalBmi = new javax.swing.JLabel();
        lblVitalTemperature = new javax.swing.JLabel();
        txtVitalTemperature = new javax.swing.JTextField();
        lblTitlePV = new javax.swing.JLabel();
        lblTitlePD = new javax.swing.JLabel();

        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Community", "Age", "Gender", "Contact number", "Street Name", "House Number", "City", "State", "Zip Code"
            }
        ));
        jScrollPane1.setViewportView(tblPerson);

        lblTitleP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitleP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleP.setText("New Patient");

        lblSearchName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSearchName.setText("Name:");

        txtSearchbyName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSearchbyName.setText("Search");
        btnSearchbyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbyNameActionPerformed(evt);
            }
        });

        txtSex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtZipCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtContactNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblZipCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblZipCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZipCode.setText("Zip Code:");

        lblContactNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContactNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContactNumber.setText("Contact Number:");

        lblStreeName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStreeName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreeName.setText("Street Name:");

        txtCommunity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityActionPerformed(evt);
            }
        });

        txtStreetName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblCommunity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCommunity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCommunity.setText("Community:");

        txtHouseNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblHouseNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHouseNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHouseNumber.setText("House Number:");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");

        txtCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");

        lblCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblState.setText("State:");

        lblSex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSex.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSex.setText("Gender:");

        txtState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnFirstEncounter.setText("Add Patient's First Encounter");
        btnFirstEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstEncounterActionPerformed(evt);
            }
        });

        btnPersonAsPatient.setText("Add Person as Patient");
        btnPersonAsPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonAsPatientActionPerformed(evt);
            }
        });

        lblVitalBloodPressure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalBloodPressure.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalBloodPressure.setText("Blood Pressure:");

        txtVitalBloodPressure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblVitalSugar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalSugar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalSugar.setText("Sugar Level:");

        txtVitalSugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtVitalHeartRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblVitalHeartRate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalHeartRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalHeartRate.setText("Heart Rate:");

        txtVitalBmi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblVitalBmi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalBmi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalBmi.setText("BMI:");

        lblVitalTemperature.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalTemperature.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVitalTemperature.setText("Temperature:");

        txtVitalTemperature.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTitlePV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitlePV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePV.setText("Patient's Vitals");

        lblTitlePD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitlePD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePD.setText("Patient's Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleP, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchbyName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnSearchbyName))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVitalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVitalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVitalHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVitalHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVitalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVitalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVitalSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVitalSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVitalBmi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVitalBmi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btnFirstEncounter))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStreeName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitlePV, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitlePD, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPersonAsPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(387, 387, 387)))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtVitalBmi, txtVitalSugar, txtZipCode});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtCity, txtCommunity, txtContactNumber, txtHouseNumber, txtName, txtSex, txtState, txtStreetName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtVitalBloodPressure, txtVitalHeartRate, txtVitalTemperature});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitleP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchbyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchName)
                    .addComponent(btnSearchbyName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPersonAsPatient)
                .addGap(18, 18, 18)
                .addComponent(lblTitlePD)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreeName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblTitlePV)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVitalSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVitalSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVitalBmi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVitalBmi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVitalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVitalBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVitalHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVitalHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVitalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVitalTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFirstEncounter))
                .addGap(38, 38, 38))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtVitalBmi, txtVitalSugar, txtZipCode});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAge, txtCity, txtCommunity, txtContactNumber, txtHouseNumber, txtName, txtSex, txtState, txtStreetName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtVitalBloodPressure, txtVitalHeartRate, txtVitalTemperature});

    }// </editor-fold>//GEN-END:initComponents

    private void txtCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityActionPerformed

    private void btnPersonAsPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonAsPatientActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblPerson.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please Select a row to Add!!!");
            return;
        } 

        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        Person selectedPerson = (Person) model.getValueAt(selectedRowIndex, 0);
        
        House houseForAdd = selectedPerson.getHouse();
        
        boolean checkPatient;
        
        checkPatient = patientDirectory.isAlreadyPatient(selectedPerson);
        if(checkPatient == true){
            JOptionPane.showMessageDialog(this, "Person Already as Patient!! \n Use 'Patient Encounter' Button!!!");
            
        }
        else{
            
            txtCommunity.setText(houseForAdd.getCommunity());
            txtName.setText(selectedPerson.getPersonName());
            txtContactNumber.setText(String.valueOf(selectedPerson.getPersonContactNumber()));
            txtAge.setText(String.valueOf(selectedPerson.getPersonAge()));
            txtSex.setText(selectedPerson.getPersonSex());
            txtStreetName.setText(houseForAdd.getStreetName());
            txtHouseNumber.setText(String.valueOf(houseForAdd.getHouseNumber()));
            txtCity.setText(houseForAdd.getCity());
            txtState.setText(houseForAdd.getState());
            txtZipCode.setText(String.valueOf(houseForAdd.getZipCode()));
            
            
        }
    }//GEN-LAST:event_btnPersonAsPatientActionPerformed

    private void btnFirstEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstEncounterActionPerformed
        // TODO add your handling code here:
        
        String communityName = txtCommunity.getText();
        String name = txtName.getText();
        long contactNumber = Long.parseLong(txtContactNumber.getText());
        int age = Integer.parseInt(txtAge.getText());
        String sex = txtSex.getText();
        String streetName = txtStreetName.getText();
        int houseNumber = Integer.parseInt(txtHouseNumber.getText());
        String city = txtCity.getText();
        String state = txtState.getText();
        int zipCode = Integer.parseInt(txtZipCode.getText());
        int bloodPressure = Integer.parseInt(txtVitalBloodPressure.getText());
        int sugar = Integer.parseInt(txtVitalSugar.getText());
        int heartRate = Integer.parseInt(txtVitalHeartRate.getText());
        int bmi = Integer.parseInt(txtVitalBmi.getText());
        int temperature = Integer.parseInt(txtVitalTemperature.getText());
        boolean checkId; 
        
        Patient patient = patientDirectory.addPatient();
        House houseForPatient = new House();
        VitalSigns vs = new VitalSigns();
        
        int pId;
        while(true){
            Random rand = new Random();
            int rand_int = rand.nextInt(1000);
            checkId = patientDirectory.isAlreadyPatientId(rand_int);
            if(checkId == false){
                pId = rand_int;
                break;
            }
        }
        
        patient.setPatientId(pId);
        patient.setPatientName(name);
        patient.setPatientAge(age);
        patient.setPatientContactNumber(contactNumber);
        patient.setPatientSex(sex);
        
        houseForPatient.setCommunity(communityName);
        houseForPatient.setStreetName(streetName);
        houseForPatient.setHouseNumber(houseNumber);
        houseForPatient.setCity(city);
        houseForPatient.setState(state);
        houseForPatient.setZipCode(zipCode);
        patient.setHouse(houseForPatient);
        
        vs.setBloodPressure(bloodPressure);
        vs.setHeartRate(heartRate);
        vs.setSugar(sugar);
        vs.setBmi(bmi);
        vs.setTemperature(temperature);
        patient.setVitals(vs);
        
        int first = 1;
        
        Encounter firstEncounterInHistory = encounterHistory.addEncounter();
        firstEncounterInHistory.setEncounterNumber(first);
        Patient patientForEncounter = new Patient();
        House houseForEncounter = new House();
        VitalSigns vsForEncounter = new VitalSigns();
        
        patientForEncounter.setPatientId(pId);
        patientForEncounter.setPatientName(name);
        patientForEncounter.setPatientAge(age);
        patientForEncounter.setPatientContactNumber(contactNumber);
        patientForEncounter.setPatientSex(sex);
        
        houseForEncounter.setCommunity(communityName);
        houseForEncounter.setStreetName(streetName);
        houseForEncounter.setHouseNumber(houseNumber);
        houseForEncounter.setCity(city);
        houseForEncounter.setState(state);
        houseForEncounter.setZipCode(zipCode);
        patientForEncounter.setHouse(houseForPatient);
        
        vsForEncounter.setBloodPressure(bloodPressure);
        vsForEncounter.setHeartRate(heartRate);
        vsForEncounter.setSugar(sugar);
        vsForEncounter.setBmi(bmi);
        vs.setTemperature(temperature);
        patientForEncounter.setVitals(vs); 
        
        firstEncounterInHistory.setEncounterPatient(patientForEncounter);
        
        JOptionPane.showMessageDialog(this, "New Patient added successfully!! \n And Your Patient Id is:" + pId);
        
        populatePersonTable();
        
        txtSearchbyName.setText("");
        txtCommunity.setText("");
        txtName.setText("");
        txtContactNumber.setText("");
        txtAge.setText("");
        txtSex.setText("");
        txtStreetName.setText("");
        txtHouseNumber.setText("");
        txtCity.setText("");
        txtState.setText("");
        txtZipCode.setText("");
        txtVitalBloodPressure.setText("");
        txtVitalBmi.setText("");
        txtVitalHeartRate.setText("");
        txtVitalSugar.setText("");
        txtVitalTemperature.setText("");
        
        
    }//GEN-LAST:event_btnFirstEncounterActionPerformed

    private void btnSearchbyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbyNameActionPerformed
        // TODO add your handling code here:
        String searchPersonName = txtSearchbyName.getText();
        
        if(searchPersonName.isBlank() || searchPersonName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Name");
        }
        else{
            List<Person> searchedPersonByName = personDirectory.findPersonByName(searchPersonName);
            populateSearchResults(searchedPersonByName); 
        }
        
    }//GEN-LAST:event_btnSearchbyNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstEncounter;
    private javax.swing.JButton btnPersonAsPatient;
    private javax.swing.JButton btnSearchbyName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblHouseNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSearchName;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreeName;
    private javax.swing.JLabel lblTitleP;
    private javax.swing.JLabel lblTitlePD;
    private javax.swing.JLabel lblTitlePV;
    private javax.swing.JLabel lblVitalBloodPressure;
    private javax.swing.JLabel lblVitalBmi;
    private javax.swing.JLabel lblVitalHeartRate;
    private javax.swing.JLabel lblVitalSugar;
    private javax.swing.JLabel lblVitalTemperature;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTable tblPerson;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtHouseNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearchbyName;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetName;
    private javax.swing.JTextField txtVitalBloodPressure;
    private javax.swing.JTextField txtVitalBmi;
    private javax.swing.JTextField txtVitalHeartRate;
    private javax.swing.JTextField txtVitalSugar;
    private javax.swing.JTextField txtVitalTemperature;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void populatePersonTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        model.setRowCount(0);
       
        for(Person p: personDirectory.getPersonDirectory()){
            Object[] row = new Object[10];
            
            House h = p.getHouse();
            
            row[0] = p;
            row[1] = h.getCommunity();
            row[2] = p.getPersonAge();
            row[3] = p.getPersonSex();
            row[4] = p.getPersonContactNumber();
            row[5] = h.getStreetName();
            row[6] = h.getHouseNumber();
            row[7] = h.getCity();
            row[8] = h.getState();
            row[9] = h.getZipCode();
            
            model.addRow(row);
        }
    }

    private void populatePatientTable(){
        
    }

    private void populateEncounterTable(){
        
        
        
    }
    
    private void populateSearchResults(List<Person> searchedPerson){
        
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        model.setRowCount(0);
        
         for(Person pp: searchedPerson){
             
             Object[] row = new Object[10];
            
            House h = pp.getHouse();
            
            row[0] = pp;
            row[1] = h.getCommunity();
            row[2] = pp.getPersonAge();
            row[3] = pp.getPersonSex();
            row[4] = pp.getPersonContactNumber();
            row[5] = h.getStreetName();
            row[6] = h.getHouseNumber();
            row[7] = h.getCity();
            row[8] = h.getState();
            row[9] = h.getZipCode();
            
            model.addRow(row);
         }
    }
}
